routes/web.php
<?php

Route::get('/', 'PagesController@index')->name('featured');
Route::get('/eventos', 'PagesController@eventos')->name('eventos');
Route::get('/evento/{event}', 'PagesController@evento')->name('evento');
Route::get('/estabelecimentos', 'PagesController@estabelecimentos')->name('estabelecimentos');
Route::get('/estabelecimento/{enterprise}', 'PagesController@estabelecimento')->name('estabelecimento');
Route::post('/set_city', 'PagesController@set_city')->name('set_city');

Auth::routes();

Route::group(['middleware' => ['auth']], function () {
    Route::get('/home', 'PagesController@home')->name('home');
    Route::resource('/enterprises', 'EnterprisesController');
    Route::resource('/events', 'EventsController');
    Route::resource('/users', 'UsersController');
    Route::post('/events/{event}/status', 'EventsController@status')->name('events.status');
    Route::resource('/types', 'EventTypesController');
    Route::get('/profile', 'ProfileController@show')->name('profile');
    Route::get('/profile/edit', 'ProfileController@edit')->name('profile.edit');
    Route::put('/profile/', 'ProfileController@update')->name('profile.update');
});

app/Http/Controllers/EnterprisesController.php
<?php

namespace App\Http\Controllers;

use App\Enterprise;
use App\Http\Requests\SaveEnterprise;
use Illuminate\Http\Request;
use Auth;
use Storage;
use Image;

class EnterprisesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = Auth::user();
        if ($user->is_admin):
            $enterprises = Enterprise::all();
        else:
            $enterprises = $user->enterprises;
        endif;
        return view('enterprises.index')->with(['enterprises' => $enterprises]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $user = Auth::user();
        $enterprise = new Enterprise();
        $enterprise->user_id = $user->id;
        return view('enterprises.create')->with(['enterprise' => $enterprise]);
    }

    /**
     * @param SaveEnterprise $request
     * @return \Illuminate\Http\Response
     */
    public function store(SaveEnterprise $request)
    {
        $user = Auth::user();
        $enterprise = new Enterprise($request->all());
        $enterprise->user_id = $user->id;

        if ($request->hasFile('logo')) {
            $file = $request->file('logo');

            $path = $file->hashName('public/logos');

            $image = Image::make($file);
            $image->fit(300, 300, function ($constraint) {
                $constraint->aspectRatio();
            });

            Storage::put($path, (string)$image->encode());
            $enterprise->logo = Storage::url($path);
        }

        $enterprise->save();
        return redirect(route('enterprises.show', $enterprise));
    }

    /**
     * Display the specified resource.
     *
     * @param  Enterprise $enterprise
     * @return \Illuminate\Http\Response
     */
    public function show(Enterprise $enterprise)
    {
        return view('enterprises.show')->with(['enterprise' => $enterprise]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  Enterprise $enterprise
     * @return \Illuminate\Http\Response
     */
    public function edit(Enterprise $enterprise)
    {
        return view('enterprises.edit')->with(['enterprise' => $enterprise]);
    }

    /**
     * Update the specified resource in storage.
     * @param SaveEnterprise $request
     * @param  Enterprise $enterprise
     * @return \Illuminate\Http\Response
     */
    public function update(SaveEnterprise $request, Enterprise $enterprise)
    {
        $enterprise->fill($request->all());

        if ($request->hasFile('logo')) {
            $file = $request->file('logo');

            $path = $file->hashName('public/logos');

            $image = Image::make($file);
            $image->fit(300, 300, function ($constraint) {
                $constraint->aspectRatio();
            });

            Storage::put($path, (string)$image->encode());
            $enterprise->logo = Storage::url($path);
        }

        $enterprise->save();
        return redirect(route('enterprises.show', $enterprise));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  Enterprise $enterprise
     * @return \Illuminate\Http\Response
     */
    public function destroy(Enterprise $enterprise)
    {
        $enterprise->delete();
        return redirect(route('enterprises.index'))
            ->with(['message' => 'Estabelecimento removido com sucesso']);
    }
}

resources/views/enterprises/_form.blade.php
<?php
$_user = Auth::user();
?>
<form method="POST" enctype="multipart/form-data" action="{{$action}}">
    <div class="form-group">
        <label for="name">Nome *</label>
        <input type="text" class="form-control" id="title" name="name"
               value="{{old('name', $enterprise->name)}}" placeholder="Nome do estabelecimento">
        @if ($errors->has('name'))
            <span class="help-block">
                <strong class="text-danger">{{ $errors->first('name') }}</strong></span>
        @endif
    </div>

    <div class="form-group">
        <label for="location">Endereço *</label>
        <input type="text" class="form-control" id="address" name="address"
               value="{{old('address', $enterprise->address)}}" placeholder="Endereço do estabelecimento">
        @if ($errors->has('address'))
            <span class="help-block">
                <strong class="text-danger">{{ $errors->first('address') }}</strong></span>
        @endif
    </div>

    <div class="form-row">
        <div class="form-group col">
            <label for="location">Cidade *</label>
            <input type="text" class="form-control" id="location" name="location"
                   value="{{old('location', $enterprise->location)}}" placeholder="Cidade do estabelecimento">
            @if ($errors->has('location'))
                <span class="help-block">
                    <strong class="text-danger">{{ $errors->first('location') }}</strong></span>
            @endif
        </div>
    </div>


    <div class="form-group">
        <label for="attendance">Atendimento </label>
        <input type="text" class="form-control" id="attendance" name="attendance"
               value="{{old('attendance', $enterprise->attendance)}}" placeholder="Terça a domingo, das 20 às 03h">
        @if ($errors->has('attendance'))
            <span class="help-block">
                    <strong class="text-danger">{{ $errors->first('attendance') }}</strong></span>
        @endif
    </div>
    <div class="form-group">
        <label for="cep">CEP</label>
        <input type="text" class="form-control" id="cep" name="cep" maxlength="9"
               value="{{old('cep', $enterprise->cep)}}" placeholder="*****-***">
        @if ($errors->has('cep'))
            <span class="help-block">
                    <strong class="text-danger">{{ $errors->first('cep') }}</strong></span>
        @endif
    </div>

    <div class="form-group">
        <label for="owner">Dono/Responsável</label>
        <input type="text" class="form-control" id="owner" name="owner"
               value="{{old('owner', $enterprise->owner)}}" placeholder="Nome do responsável pelo estabelecimento">
        @if ($errors->has('owner'))
            <span class="help-block">
                    <strong class="text-danger">{{ $errors->first('owner') }}</strong></span>
        @endif
    </div>

    <div class="form-group">
        <label for="link">Site</label>
        <input type="text" class="form-control" id="link" name="link"
               value="{{old('link', $enterprise->link)}}" placeholder="Link externo do estabelecimento">
        @if ($errors->has('link'))
            <span class="help-block">
                    <strong class="text-danger">{{ $errors->first('link') }}</strong></span>
        @endif
    </div>
    <div class="form-group">
        <label for="maps">Google Maps</label>
        <input type="text" class="form-control" id="maps" name="maps"
               value="{{old('maps', $enterprise->maps)}}" placeholder="Link de compartilhamento pelo google maps">
        @if ($errors->has('maps'))
            <span class="help-block">
                    <strong class="text-danger">{{ $errors->first('maps') }}</strong></span>
        @endif
    </div>
    <div class="form-row">
        <div class="form-group col-12 col-sm-6 col-md-8">
            <label for="logo">Logomarca</label>
            <input type="file" class="form-control-file" id="logo" name="logo" accept=".png, .jpg, .jpeg"
                   value="{{old('logo')}}">
            @if ($errors->has('logo'))
                <span class="help-block">
                    <strong class="text-danger">{{ $errors->first('logo') }}</strong></span>
            @endif
        </div>
        <div class="col-12 col-sm-6 col-md-8">
            @if($enterprise->logo)
                <img src="{{$enterprise->logo}}" class="w-100 img-responsive" style="max-width: 150px">
            @endif
        </div>
    </div>


    {{$enterprise->id ? method_field('PUT'): ''}}
    {{csrf_field()}}
    <button type="submit" class="btn btn-primary">Enviar</button>

</form>

resources/views/enterprises/create.blade.php
@extends('template')

@section('content')
    <div class="w-100 d-flex justify-content-between my-3">
        <div class="h5">Novo Estabelecimemto</div>
        <div class="">
            <a href="/enterprises" class="btn btn-sm btn-outline-warning">
                <i class="fa fa-arrow-circle-left"></i> Voltar</a>
        </div>
    </div>

    @include('enterprises._form', ['enterprise' => $enterprise, 'action' => route('enterprises.store')])

@endsection
@section('js')
    <script>
        function initialize() {
            var autoCompleteInput = document.getElementById('location');
            var autoCompleteOpcoes = {
                types: ['(cities)']
            };
            autocomplete = new google.maps.places.Autocomplete(autoCompleteInput, autoCompleteOpcoes);
        }
        google.maps.event.addDomListener(window, 'load', initialize);
    </script>
@endsection

resources/views/enterprises/edit.blade.php
@extends('template')

@section('content')
    <div class="w-100 d-flex justify-content-between my-3">
        <div class="h5">{{$enterprise->name}}</div>
        <div class="">
            <a href="/enterprises" class="btn btn-sm btn-outline-warning">
                <i class="fa fa-arrow-circle-left"></i> Voltar</a>
        </div>
    </div>

    @include('enterprises._form', ['enterprise' => $enterprise, 'action' => route('enterprises.update', $enterprise)])

@endsection
@section('js')
    <script>
        function initialize() {
            var autoCompleteInput = document.getElementById('location');
            var autoCompleteOpcoes = {
                types: ['(cities)']
            };
            autocomplete = new google.maps.places.Autocomplete(autoCompleteInput, autoCompleteOpcoes);
        }
        google.maps.event.addDomListener(window, 'load', initialize);
    </script>
@endsection

resources/views/enterprises/index.blade.php
@extends('template')

@section('content')
    <div class="w-100 d-flex justify-content-between my-3">
        <div class="h5">Seus estabelecimentos</div>
        <div class="buttons">
            <a href="/enterprises/create" class="btn btn-sm btn-outline-primary">
                <i class="fa fa-plus-circle"></i> Novo estabelecimento</a>
            <a href="/home" class="btn btn-sm btn-outline-secondary">
                <i class="fa fa-bar-chart"></i> Visão geral</a>
        </div>
    </div>

    <table class="table table-striped datatable init" cellspacing="0" width="100%">
        <thead>
        <tr>
            <th>Nome</th>
            <th>Cidade</th>
            <th> Detalhes</th>
            <th>Ações</th>
        </tr>
        </thead>
        <tbody>
        @foreach($enterprises as $enterprise)
            <tr>
                <td>{{$enterprise->name}}</td>
                <td>{{$enterprise->location }}</td>
                <td>
                    <div class="d-flex justify-content-start">
                        <img class="iconized" src="{{$enterprise->logo}}">
                        <ul style="font-size: 9pt;">
                            <li>{{$enterprise->owner}}</li>
                            <li>{{$enterprise->link}}</li>
                            <li>{{$enterprise->attendance}}</li>
                        </ul>
                    </div>
                </td>
                <td>
                    <a href="/enterprises/{{$enterprise->id}}" class="btn btn-sm btn-outline-secondary">
                        <i class="fa fa-search"></i></a>
                    <a href="/enterprises/{{$enterprise->id}}/edit" class="btn btn-sm btn-outline-secondary">
                        <i class="fa fa-pencil"></i></a>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
@endsection

resources/views/enterprises/show.blade.php
@extends('template')

@section('content')
    <div class="w-100 d-flex justify-content-between my-3">
        <div class="h5">{{$enterprise->name}}</div>
        <div class="buttons">
            <a href="/enterprises" class="btn btn-outline-warning  btn-sm ">
                <i class="fa fa-arrow-circle-left"></i> Voltar</a>

            <a href="/enterprises/{{$enterprise->id}}/edit" class="btn btn-sm btn-outline-secondary">
                <i class="fa fa-pencil"></i> Editar</a>

            <button type="button" class="btn btn-sm btn-outline-danger" data-toggle="modal"
                    data-target="#deleteEventModal">
                <i class="fa fa-close"></i> Remover
            </button>

            <!-- Modal -->
            <div class="modal fade" id="deleteEventModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
                 aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="deleteModalLabel">Excluir estabelecimento</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <p> Tem certeza que deseja remover este estabelecimento?</p>
                            <p><strong> Obs: TODOS OS EVENTOS DESTE ESTABELECIMENTO SERÃO REMOVIDOS! </strong></p>
                            <p>Não será possível desfazer esta ação.</p>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">
                                Fechar
                            </button>
                            <form action="{{route('enterprises.destroy', [$enterprise])}}" method="POST">
                                <button type="submit" class="btn btn-danger">
                                    <i class="fa fa-close"></i> Excluir Estabelecimento
                                </button>
                                <?= method_field('DELETE') ?>
                                <?= csrf_field() ?>
                            </form>
                        </div>
                    </div>
                </div>
            </div>


        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <?php $fields = [
                'name',
                'address',
                'location',
                'attendance',
                'cep',
                'owner',
                'link',
            ]?>
            <table class="table">
                @foreach($fields as $attr)
                    <tr class="">
                        <td class="text-capitalize font-weight-light text-muted text-right">
                            @lang('attributes.'.$attr):
                        </td>
                        <td>{{$enterprise->$attr}}</td>
                    </tr>
                @endforeach
                <tr class="">
                    <td class="text-capitalize font-weight-light text-muted text-right">Logomarca</td>
                    <td><img src="{{$enterprise->logo}}" style="max-width: 200px"></td>
                </tr>
            </table>
        </div>
        @if($enterprise->maps)
            <div class="col-md-6">
                <h5>Como chegar: </h5>
                <iframe src="{{$enterprise->maps}}" width="100%" height="300px"
                        frameborder="0" style="border:0" allowfullscreen></iframe>
            </div>
        @endif
    </div>
@endsection