routes/web.php
<?php

Route::get('/', 'PagesController@index')->name('featured');
Route::get('/eventos', 'PagesController@eventos')->name('eventos');
Route::get('/evento/{event}', 'PagesController@evento')->name('evento');
Route::get('/estabelecimentos', 'PagesController@estabelecimentos')->name('estabelecimentos');
Route::get('/estabelecimento/{enterprise}', 'PagesController@estabelecimento')->name('estabelecimento');
Route::post('/set_city', 'PagesController@set_city')->name('set_city');

Auth::routes();

Route::group(['middleware' => ['auth']], function () {
    Route::get('/home', 'PagesController@home')->name('home');
    Route::resource('/enterprises', 'EnterprisesController');
    Route::resource('/events', 'EventsController');
    Route::resource('/users', 'UsersController');
    Route::post('/events/{event}/status', 'EventsController@status')->name('events.status');
    Route::resource('/types', 'EventTypesController');
    Route::get('/profile', 'ProfileController@show')->name('profile');
    Route::get('/profile/edit', 'ProfileController@edit')->name('profile.edit');
    Route::put('/profile/', 'ProfileController@update')->name('profile.update');
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function events()
    {
        return $this->hasMany('App\Event');
    }

    public function enterprises()
    {
        return $this->hasMany('App\Enterprise');
    }
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;

class UsersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all();
        return view('users.index')->with(['users' => $users]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $user = new User();
        return view('users.create')->with(['user' => $user]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

    }

    /**
     * Display the specified resource.
     *
     * @param  User $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        return view('users.show')->with(['user' => $user]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  User $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        return view('users.create')->with(['user' => $user]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  User $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  User $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        //
    }
}

resources/views/users/edit.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: dalponte
 * Date: 30/05/2018
 * Time: 10:24
 */

resources/views/users/index.blade.php
@extends('template')

@section('content')
    <div class="w-100 d-flex justify-content-between my-3">
        <div class="h5">Usuários</div>
        <div class="buttons">
            <a href="/home" class="btn btn-sm btn-outline-secondary">
                <i class="fa fa-bar-chart"></i> Visão geral</a>
        </div>
    </div>

    <table class="table table-striped datatable init" cellspacing="0" width="100%">
        <thead>
        <tr>
            <th>Nome</th>
            <th>E-mail</th>
            <th>Ações</th>
        </tr>
        </thead>
        <tbody>
        @foreach($users as $user)
            <tr>
                <td>{{ $user->name }}</td>
                <td>{{ $user->email }}</td>
                <td>
                    <a href="/users/{{ $user->id }}" class="btn btn-sm btn-outline-secondary">
                        <i class="fa fa-search"></i></a>
                    <a href="/users/{{ $user->id }}/edit" class="btn btn-sm btn-outline-secondary disabled"
                       disabled="disabled">
                        <i class="fa fa-pencil"></i></a>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
@endsection

resources/views/users/show.blade.php
@extends('template')

@section('content')
    <div class="w-100 d-flex justify-content-between my-3">
        <div class="h5">{{$user->name}}</div>
        <div class="buttons">
            <a href="/users" class="btn btn-outline-warning  btn-sm ">
                <i class="fa fa-arrow-circle-left"></i> Voltar</a>

            <a href="/users/{{$user->id}}/edit" class="btn btn-sm btn-outline-secondary">
                <i class="fa fa-pencil"></i> Editar</a>

            <button type="button" class="btn btn-sm btn-outline-danger" data-toggle="modal"
                    data-target="#deleteEventModal">
                <i class="fa fa-close"></i> Remover
            </button>

            <!-- Modal -->
            <div class="modal fade" id="deleteEventModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
                 aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="deleteModalLabel">Excluir estabelecimento</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <p> Tem certeza que deseja remover este usuário?</p>
                            <p>Não será possível desfazer esta ação.</p>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">
                                Fechar
                            </button>
                            <form action="{{route('users.destroy', [$user])}}" method="POST">
                                <button type="submit" class="btn btn-danger disabled" disabled="disabled">
                                    <i class="fa fa-close"></i> Excluir Usuário
                                </button>
                                <?= method_field('DELETE') ?>
                                <?= csrf_field() ?>
                            </form>
                        </div>
                    </div>
                </div>
            </div>


        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <?php $fields = [
                'name',
                'email',
                'phone',
            ];?>
            <table class="table">
                @foreach($fields as $attr)
                    <tr class="">
                        <td class="text-capitalize font-weight-light text-muted text-right">
                            @lang('attributes.'.$attr):
                        </td>
                        <td>{{$user->$attr}}</td>
                    </tr>
                @endforeach
            </table>
        </div>
        <div class="col-md-6">
            <hr>
            <h5>Eventos do usuário</h5>
            <ul class="list-group">
                @foreach($user->events as $event)
                    <li class="list-group-item">
                        <a href="{{route('events.show', [$event])}}">{{$event->title}}</a>
                        <br>
                        <small>{{$event->beginning}}</small>
                        <br>
                        <small>{{$event->location}}</small>
                    </li>
                @endforeach
            </ul>
        </div>
    </div>
@endsection