routes/web.php
<?php

Route::get('/', 'PagesController@index')->name('featured');
Route::get('/eventos', 'PagesController@eventos')->name('eventos');
Route::get('/evento/{event}', 'PagesController@evento')->name('evento');
Route::get('/estabelecimentos', 'PagesController@estabelecimentos')->name('estabelecimentos');
Route::get('/estabelecimento/{enterprise}', 'PagesController@estabelecimento')->name('estabelecimento');
Route::post('/set_city', 'PagesController@set_city')->name('set_city');

Auth::routes();

Route::group(['middleware' => ['auth']], function () {
    Route::get('/home', 'PagesController@home')->name('home');
    Route::resource('/enterprises', 'EnterprisesController');
    Route::resource('/events', 'EventsController');
    Route::resource('/users', 'UsersController');
    Route::post('/events/{event}/status', 'EventsController@status')->name('events.status');
    Route::resource('/types', 'EventTypesController');
    Route::get('/profile', 'ProfileController@show')->name('profile');
    Route::get('/profile/edit', 'ProfileController@edit')->name('profile.edit');
    Route::put('/profile/', 'ProfileController@update')->name('profile.update');
});

app/Event.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

/**
 * Class Event
 * @package App
 * @property integer id
 * @property string title
 * @property integer status
 * @property Carbon beginning
 * @property Carbon ending
 * @property string description
 * @property string location
 * @property string city
 * @property string keywords
 * @property integer enterprise_id
 * @property integer type_id
 * @property integer user_id
 */
class Event extends Model
{
    protected $fillable = [
        'title',
        'status',
        'beginning',
        'ending',
        'description',
        'city',
        'location',
        'keywords',
        'enterprise_id',
        'type_id',
        'user_id',
    ];

    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function enterprise()
    {
        return $this->belongsTo('App\Enterprise');
    }

    public function type()
    {
        return $this->belongsTo('App\EventType');
    }
}

app/EventType.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class EventType extends Model
{
    protected $fillable = [
        'title',
        'description',
    ];

    public function events()
    {
        return $this->hasMany('App\Event');
    }
}

app/Http/Controllers/EventsController.php
<?php

namespace App\Http\Controllers;

use App\Event;
use App\Http\Requests\SaveEvent;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Storage;
use Image;

class EventsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = Auth::user();
        $events = Event::all();
        return view('events.events_index')->with(['events' => $events]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $event = new Event();
        return view('events.events_create')->with(['event' => $event]);
    }

    /**
     * @param SaveEvent $request
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function store(SaveEvent $request)
    {
        $event = new Event($request->all());
        $user = Auth::user();
        if ($request->hasFile('cover')) {
            $file = $request->file('cover');

            $path = $file->hashName('public/covers');

            $image = Image::make($file);
            $image->fit(1200, 600, function ($constraint) {
                $constraint->aspectRatio();
            });

            Storage::put($path, (string)$image->encode());
            $event->cover = Storage::url($path);
        }

        $event->status = 0;
        $event->user_id = $user->id;
        $event->save();
        return redirect(route('events.show', $event));
    }

    /**
     * Display the specified resource.
     *
     * @param  Event $event
     * @return \Illuminate\Http\Response
     */
    public function show(Event $event)
    {
        return view('events.events_show')->with(['event' => $event]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  Event $event
     * @return \Illuminate\Http\Response
     * @throws \Exception
     */
    public function edit(Event $event)
    {
        $user = Auth::user();
        if ($user->id != $event->user_id && !$user->is_admin)
            throw new \Exception('Você não pode visualizar esta página');
        return view('events.events_edit')->with(['event' => $event]);
    }

    /**
     * @param SaveEvent $request
     * @param Event $event
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     * @throws \Exception
     */
    public function update(SaveEvent $request, Event $event)
    {
        $user = Auth::user();
        if ($user->id != $event->user_id)
            throw new \Exception('VOcê não pode visualizar esta página');
        $event->user_id = $user->id;
        $event->title = $request->input('title');
        $event->beginning = $request->input('beginning');
        $event->ending = $request->input('ending');
        $event->description = $request->input('description');
        $event->location = $request->input('location');
        $event->city = $request->input('city');
        $event->keywords = $request->input('keywords');
        $event->enterprise_id = $request->input('enterprise_id');
        $event->type_id = $request->input('type_id');

        if ($request->hasFile('cover')) {
            $file = $request->file('cover');

            $path = $file->hashName('public/covers');

            $image = Image::make($file);
            $image->fit(1200, 600, function ($constraint) {
                $constraint->aspectRatio();
            });

            Storage::put($path, (string)$image->encode());
            $event->cover = Storage::url($path);
        }
        $result = $event->save();
        return redirect(route('events.show', $event));
    }

    /**
     * @param Event $event
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Exception
     */
    public function destroy(Event $event)
    {
        $event->delete();
        return redirect(route('events.index'))
            ->with(['message' => 'Evento removido com sucesso']);
    }

    public function status(Request $request, Event $event)
    {
        $event->status = $request->status;
        $res = $event->save();
        return response()->json(['message' => '<b>Status atualizado</b>', 'result' => $res]);
    }

}

resources/views/events/_form.blade.php
<?php
$_user = Auth::user();
$houses = $_user->enterprises;
$types = \App\EventType::all();

$sel_houses = array_fill_keys($houses->pluck('id')->toArray(), '');
$sel_houses[$event->enterprise_id] = 'selected="selected"';
$sel_types = array_fill_keys($types->pluck('id')->toArray(), '');
$sel_types[$event->type_id] = 'selected="selected"';
$beginning = (new \Carbon\Carbon($event->beginning))->formatLocalized('%Y-%m-%dT%H:%M');
$ending = (new \Carbon\Carbon($event->ending))->formatLocalized('%Y-%m-%dT%H:%M');
?>
<form method="POST" enctype="multipart/form-data" action="{{$action}}">
    <div class="form-group">
        <label for="title">Título do evento</label>
        <input type="text" class="form-control" id="title" name="title"
               value="{{old('title', $event->title)}}" placeholder="Nome do evento">
        @if ($errors->has('title'))
            <span class="help-block">
                <strong class="text-danger">{{ $errors->first('title') }}</strong></span>
        @endif
    </div>

    <div class="form-row">
        <div class="form-group col">
            <label for="beginning">Início</label>
            <input type="datetime-local" class="form-control" id="beginning" name="beginning"
                   value="{{old('beginning', $beginning)}}">
            @if ($errors->has('beginning'))
                <span class="help-block">
                    <strong class="text-danger">{{ $errors->first('beginning') }}</strong></span>
            @endif
        </div>
        <div class="form-group col">
            <label for="ending">Termino</label>
            <input type="datetime-local" class="form-control" id="ending" name="ending"
                   value="{{old('ending', $ending)}}">
            @if ($errors->has('ending'))
                <span class="help-block">
                    <strong class="text-danger">{{ $errors->first('ending') }}</strong></span>
            @endif
        </div>
    </div>

    <div class="form-row">
        <div class="form-group col">
            <label for="enterprise_id">Estabelecimento</label>
            <select class="form-control" id="enterprise_id" name="enterprise_id">
                <option value="" class="text-muted">Nenhum</option>
                @foreach($houses as $h)
                    <option value="{{$h->id}}" {{$sel_houses[$event->enterprise_id]}}>{{$h->name}}</option>
                @endforeach
            </select>
        </div>
        <div class="form-group col">
            <label for="type_id">Tipo</label>
            <select class="form-control" id="type_id" name="type_id">
                @foreach($types as $t)
                    <option value="{{$t->id}}" {{$sel_types[$event->type_id]}}>{{$t->title}}</option>
                @endforeach
            </select>
        </div>
    </div>

    <div class="form-group">
        <label for="location">Local do evento</label>
        <input type="text" class="form-control" id="location" name="location"
               value="{{old('location', $event->location)}}" placeholder="Local do evento">
        @if ($errors->has('location'))
            <span class="help-block">
                <strong class="text-danger">{{ $errors->first('location') }}</strong></span>
        @endif
    </div>

    <div class="form-row">
        <div class="form-group col">
            <label for="city">Cidade</label>
            <input type="text" class="form-control" id="city" name="city"
                   value="{{old('city', $event->city)}}" placeholder="Cidade do evento">
            @if ($errors->has('city'))
                <span class="help-block">
                    <strong class="text-danger">{{ $errors->first('city') }}</strong></span>
            @endif
        </div>
    </div>

    <div class="form-row">
        <div class="form-group col">
            <label for="keywords">Palavras chave</label>
            <input type="text" class="form-control" id="keywords" name="keywords" data-role="tagsinput"
                   value="{{old('keywords', $event->keywords)}}" placeholder="Palavras chave ">
            @if ($errors->has('keywords'))
                <span class="help-block">
                    <strong class="text-danger">{{ $errors->first('keywords') }}</strong></span>
            @endif
            <small id="keywordsHelp" class="form-text text-muted">
                Utilize vírgulas <code>,</code> para separar cada palavra-chave
            </small>
        </div>
    </div>

    <div class="form-row">
        <div class="form-group col-12 col-sm-6 col-md-8">
            <label for="cover">Capa</label>
            <input type="file" class="form-control-file" id="cover" name="cover" accept=".png, .jpg, .jpeg"
                   value="{{old('cover')}}">
            @if ($errors->has('cover'))
                <span class="help-block">
                    <strong class="text-danger">{{ $errors->first('cover') }}</strong></span>
            @endif
        </div>
        <div class="col-12 col-sm-6 col-md-8">
            @if($event->cover)
                <img src="{{$event->cover}}" class="w-100 img-responsive" style="max-width: 150px">
            @endif
        </div>
    </div>

    <div class=" form-group">
        <label for="description">Descrição</label>
        <textarea class="form-control" id="description" name="description" rows="3"
                  placeholder="Descrição completa">{{$event->description}}</textarea>
    </div>

    {{$event->id ? method_field('PUT'): ''}}
    {{csrf_field()}}
    <button type="submit" class="btn btn-primary">Enviar</button>

</form>

resources/views/events/events_create.blade.php
@extends('template')

@section('content')
    <div class="w-100 d-flex justify-content-between my-3">
        <div class="h5">Novo evento</div>
        <div class="">
            <a href="/events" class="btn btn-sm btn-outline-warning">
                <i class="fa fa-arrow-circle-left"></i> Voltar</a>
        </div>
    </div>

    @include('events._form', ['event' => $event, 'action' => route('events.store')])

@endsection
@section('js')
    <script>
        function initialize() {
            var autoCompleteInput = document.getElementById('city');
            var autoCompleteOpcoes = {
                types: ['(cities)']
            };
            autocomplete = new google.maps.places.Autocomplete(autoCompleteInput, autoCompleteOpcoes);
        }

        google.maps.event.addDomListener(window, 'load', initialize);
    </script>
@endsection

resources/views/events/events_edit.blade.php
@extends('template')

@section('content')
    <div class="w-100 d-flex justify-content-between my-3">
        <div class="h5">{{$event->title}}</div>
        <div class="">
            <a href="/events" class="btn btn-sm btn-outline-warning">
                <i class="fa fa-arrow-circle-left"></i> Voltar</a>
        </div>
    </div>

    @include('events._form', ['event' => $event, 'action' => route('events.update', $event)])

@endsection
@section('js')
    <script>
        function initialize() {
            var autoCompleteInput = document.getElementById('city');
            var autoCompleteOpcoes = {
                types: ['(cities)']
            };
            autocomplete = new google.maps.places.Autocomplete(autoCompleteInput, autoCompleteOpcoes);
        }
        google.maps.event.addDomListener(window, 'load', initialize);
    </script>
@endsection

resources/views/events/events_index.blade.php
@extends('template')

@section('content')
    <div class="w-100 d-flex justify-content-between my-3">
        <div class="h5">Seus eventos</div>
        <div class="buttons">
            <a href="/events/create" class="btn btn-sm btn-outline-primary">
                <i class="fa fa-plus-circle"></i> Novo evento</a>
            <a href="/home" class="btn btn-sm btn-outline-secondary">
                <i class="fa fa-bar-chart"></i> Visão geral</a>
        </div>
    </div>

    <table class="table table-striped">
        <tr>
            <th>Início</th>
            <th>Título</th>
            <th>Cidade</th>
            <th>Local</th>
            <th>Ações</th>
        </tr>

        @foreach($events as $event)
            <tr>
                <td>
                    <small>{{$event->beginning}}</small>
                </td>
                <td>{{$event->title}}</td>
                <td><?= "$event->city - <small>$event->uf</small>"?></td>
                <td>{{$event->location}}</td>
                <td>
                    <a href="/events/{{$event->id}}" class="btn btn-sm btn-outline-secondary">
                        <i class="fa fa-search"></i></a>
                    <a href="/events/{{$event->id}}/edit" class="btn btn-sm btn-outline-secondary">
                        <i class="fa fa-pencil"></i></a>
                </td>
            </tr>
        @endforeach

    </table>
@endsection

resources/views/events/events_show.blade.php
@extends('template')

@section('content')
    <div class="w-100 d-flex justify-content-between my-3">
        <div class="h5">{{$event->title}}</div>
        <div class="buttons">
            <a href="/events" class="btn btn-sm btn-outline-warning">
                <i class="fa fa-arrow-circle-left"></i> Voltar</a>
            <a href="/evento/{{$event->id}}/" class="btn btn-sm btn-outline-primary">
                <i class="fa fa-eye"></i> Ver evento</a>
            <a href="/events/{{$event->id}}/edit" class="btn btn-sm btn-outline-secondary">
                <i class="fa fa-pencil"></i> Editar</a>

            <button type="button" class="btn btn-sm btn-outline-danger" data-toggle="modal"
                    data-target="#deleteEventModal">
                <i class="fa fa-close"></i> Remover
            </button>

            <!-- Modal -->
            <div class="modal fade" id="deleteEventModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
                 aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="deleteModalLabel">Excluir evento</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <p> Tem certeza que deseja remover este evento?</p>
                            <p>Não será possível desfazer esta ação.</p>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">
                                Fechar
                            </button>
                            <form action="{{route('events.destroy', [$event])}}" method="POST">
                                <button type="submit" class="btn btn-danger">
                                    <i class="fa fa-close"></i> Excluir Evento
                                </button>
                                <?= method_field('DELETE') ?>
                                <?= csrf_field() ?>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>

    @if($event->status == 0)
        <div class="alert alert-warning">
            Este evento ainda não foi aprovado pela administração. Até ser aprovado, o evento não será exibido
            na plataforma.
        </div>
    @elseif($event->status == -1)
        <div class="alert alert-danger">
            Este evento foi rejeitado pela administração. Se houver dúvidas, entre em contato para amiores
            esclarecimentos.
        </div>
    @endif

    <?php $user = Auth::user() ?>
    @if($user->is_admin)
        <div class="card bg-light mb-3">
            <div class="card-header"><strong><i class="fa fa-user-secret"></i> Administrativo: Aprovação de evento</strong></div>
            <div class="card-block p-2">
                <?php $checked = [-1 => '', 1 => '', 0 => ''];
                $checked[$event->status] = 'checked="checked"'?>
                <div class="d-flex justify-content-between">
                    <div class="custom-radio">
                        <input type="radio" name="status" id="status-disabled" class="status-field" ]
                               value="0" data-id="{{$event->id}}" data-status="0" <?= $checked[0]?>>
                        <label for="status-disabled"> Não visível</label>
                    </div>
                    <div class="custom-radio">
                        <input type="radio" name="status" id="status-enabled" class="status-field"
                               value="1" data-id="{{$event->id}}" data-status="1" <?= $checked[1]?>>
                        <label for="status-enabled"> Aprovado</label>
                    </div>
                    <div class="custom-radio">
                        <input type="radio" name="status" id="status-rejected" class="status-field"
                               value="-1" data-id="{{$event->id}}" data-status="-1" <?= $checked[-1]?>>
                        <label for="status-rejected"> Reprovado</label>
                    </div>
                </div>
                <div class="w-100 " id="statusResultBox">

                </div>
            </div>
        </div>
    @endif

    <div class="row">
        <div class="col-md-6">
            <?php $fields = [
                'title',
                'beginning',
                'ending',
                'description',
                'location',
                'city',
                'keywords',
            ]; ?>
            <table class="table">
                @foreach($fields as $attr)
                    <tr class="">
                        <td class="text-capitalize font-weight-light text-muted text-right">
                            @lang('attributes.'.$attr)
                        </td>
                        <td>{{$event->$attr}}</td>
                    </tr>
                @endforeach
            </table>
        </div>
        <div class="col-md-6">
            <img class="img-responsive w-100" src="{{$event->cover}}">
        </div>
    </div>
@endsection
@section('js')
    <script>
        $(function () {
            $('.status-field').on('change', function (ev) {
                $(ev.target).addClass('disabled');
                $(ev.target).attr('disabled', true);
                $('#statusResultBox').html('');
                $.ajax({
                    method: "POST",
                    url: "/events/" + $(this).data('id') + '/status',
                    data: {
                        id: $(this).data('id'), status: $(this).data('status'), '_token': '{{ csrf_token() }}'
                    }
                }).done(function (data) {
                    $('#statusResultBox').html(data.message);
                }).fail(function () {
                    alert("ERRO: Ocorreu um problema ao mudar a visibilidade");
                }).always(function () {
                    $(ev.target).removeClass('disabled');
                    $(ev.target).attr('disabled', false);
                });
            })
        });
    </script>
@endsection